-- AlterTable
ALTER TABLE "transactions" ADD COLUMN  "extraAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "interest" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "penaltyAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "installments" ADD COLUMN  "dueAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;

